config/routes.rb
Rails.application.routes.draw do
  
  
  

  devise_for :users
  resources :javaques
  namespace :java do
    resources :jprogresses
  end
  namespace :java do
    get 'article/index'
  end
  namespace :java do
    resources :jps
    
  end
  namespace :chems do
    get 'ionics/index'
  end
  get 'java/progress'
  get 'java/read'
  get 'java/index'
  get 'welcome/home'
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/java.rb
module Java
  def self.table_name_prefix
    'java_'
  end
end

app/models/java/jp.rb
class Java::Jp < ApplicationRecord
  has_one :jprogresss, class_name: "jprogress", foreign_key: "reference_id"
end

app/models/java/jprogress.rb
class Java::Jprogress < ApplicationRecord

 
end

app/models/javaque.rb
class Javaque < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chems/ionics_controller.rb
class Chems::IonicsController < ApplicationController
  def index
  end
end

app/controllers/java/jps_controller.rb
class Java::JpsController < ApplicationController
  before_action :set_java_jp, only: [:show, :edit, :update, :destroy]

  # GET /java/jps
  # GET /java/jps.json
  def index
    @java_jps = Java::Jp.all
  end

  # GET /java/jps/1
  # GET /java/jps/1.json
  def show

  end

  # GET /java/jps/new
  def new
    @java_jp = Java::Jp.new
  end

  # GET /java/jps/1/edit
  def edit

  end

  # POST /java/jps
  # POST /java/jps.json
  def create
    @java_jp = Java::Jp.new(java_jp_params)
    @java_jprogress = Java::Jprogress.new(java_jprogress_params)


    respond_to do |format|
      if @java_jp.save
        #format.html { redirect_to @java_jp, notice: 'Jp was successfully created.' }
        
      else
        format.html { render :new }
        format.json { render json: @java_jp.errors, status: :unprocessable_entity }
      end
    end
      
    end
  

  # PATCH/PUT /java/jps/1
  # PATCH/PUT /java/jps/1.json
  def update   
     @java_jprogress = Java::Jprogress.new(java_jprogress_params)

    respond_to do |format|
      if @java_jp.update(java_jp_params)
        if @java_jprogress.save
          format.html { redirect_to @java_jprogress, notice: 'Jprogress was successfully created.' }
          format.json { render :show, status: :ok, location: @java_jprogress }
        else
          format.json { render json: @java_jprogress.errors, status: :unprocessable_entity }
        end  
        format.html { redirect_to @java_jp, notice: 'Jp was successfully updated.' }
        format.json { render :show, status: :ok, location: @java_jp }
      else
        format.html { render :edit }
        format.json { render json: @java_jp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /java/jps/1
  # DELETE /java/jps/1.json
  def destroy
    @java_jp.destroy
    respond_to do |format|
      format.html { redirect_to java_jps_url, notice: 'Jp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_java_jp
      @java_jp = Java::Jp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def java_jp_params
      params.require(:java_jp).permit(:heading, :ques, :ans, :input, :output, :point, :editor)
    end

    def set_java_jprogress
      @java_jprogress = Java::Jprogress.find(params[:id])
    end

    def java_jprogress_params
      params.require(:java_jprogress).permit(:heading, :ques, :ans, :point, :input, :output)
    end
end

app/controllers/java_controller.rb
class JavaController < ApplicationController
  def read
  end

  def index
  end
 
  def progress
   
  end 
 

 
end

app/controllers/javaques_controller.rb
class JavaquesController < ApplicationController
  before_action :set_javaque, only: [:show, :edit, :update, :destroy]

  # GET /javaques
  # GET /javaques.json
  def index
    @javaques = Javaque.all
  end

  # GET /javaques/1
  # GET /javaques/1.json
  def show
  end

  # GET /javaques/new
  def new
    @javaque = Javaque.new
  end

  # GET /javaques/1/edit
  def edit
  end

  # POST /javaques
  # POST /javaques.json
  def create
    @javaque = Javaque.new(javaque_params)

    respond_to do |format|
      if @javaque.save
        format.html { redirect_to @javaque, notice: 'Javaque was successfully created.' }
        format.json { render :show, status: :created, location: @javaque }
      else
        format.html { render :new }
        format.json { render json: @javaque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /javaques/1
  # PATCH/PUT /javaques/1.json
  def update
    respond_to do |format|
      if @javaque.update(javaque_params)
        format.html { redirect_to @javaque, notice: 'Javaque was successfully updated.' }
        format.json { render :show, status: :ok, location: @javaque }
      else
        format.html { render :edit }
        format.json { render json: @javaque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /javaques/1
  # DELETE /javaques/1.json
  def destroy
    @javaque.destroy
    respond_to do |format|
      format.html { redirect_to javaques_url, notice: 'Javaque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_javaque
      @javaque = Javaque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def javaque_params
      params.require(:javaque).permit(:heading, :question, :answer, :input, :output, :point)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chems/ionics_helper.rb
module Chems::IonicsHelper
end

app/helpers/java/article_helper.rb
module Java::ArticleHelper
end

app/helpers/java/jprogresses_helper.rb
module Java::JprogressesHelper
end

app/helpers/java/jps_helper.rb
module Java::JpsHelper
end

app/helpers/java_helper.rb
module JavaHelper
end

app/helpers/javaques_helper.rb
module JavaquesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/javacat/start.html.erb
<div class="pos">
<div class="card text-center">
  <div class="card-header bg-dark text-white">
    Prefer Language
  </div>
  <div class="card-body">
    <h1 class="card-title text-danger">Java</h1>
    <h3 class="card-text">Java is a general-purpose computer-programming language that is concurrent, class-based, object-oriented, and specifically designed to have as few implementation dependencies as possible.</h3>
    <h2><%= link_to  "Continue Reading", java_read_path, class: "btn btn-warning" %></h2>
  </div>
  <div class="card-footer text-muted bg-dark text-primary">
    You visted on 02/07/2018
   </div>
</div>
</div>
      <!-->
      <!-->
      

     <div class="pos2"> 
 <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Practice</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto">Java is a general-purpose computer-programming language that is concurrent, class-based, object-oriented, and specifically designed to have as few implementation dependencies as possible.<br>
        <%= link_to "Practice", java_jps_path,class: "btn btn-warning"%>
            </div>
            <%= image_tag "jpic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>


        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-success">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Challenge</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 11</div>
              <p class="card-text mb-auto">I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup <br><br>
       <%= link_to "Challenge",  java_jps_path,class: "btn btn-warning"%>  
          </p>
             
            </div>
           
            <%= image_tag  "ppic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>

      </div>



      
 <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-danger">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Progress</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto">Java is a general-purpose computer-programming language that is concurrent, class-based, .<br><br>
        <%= link_to "Progress",  java_jps_path,class: "btn btn-warning"%></p>
            </div>
            
            <%= image_tag "jpic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>


        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-info">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Contribute</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 11</div>
              <p class="card-text mb-auto">I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little .<br><br>
<%= link_to "Proceed",  java_jps_path,class: "btn btn-warning"%>
          </p>
             
            </div>
           
            <%= image_tag  "ppic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>
        
      </div>
</div>

app/views/layouts/_foot.html.erb
 <footer class="blog-footer">
      <p> built for <a href="https://repairbuck.com/">Matriculate</a> by <a href="https://fb.com/ashutosh34892">amxdp18</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/layouts/_navbar.html.erb

  
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted container btn-md btn-warning" style="margin-left:10px" href="#">Subscribe</a>
          </div>
          
          <div class="col-4 text-center">
            
            <%= link_to  "Matriculate", root_path, class: "blog-header-logo text-dark" %>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted constainer" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
           
             <%= link_to  "Sign Up", new_user_registration_path, class: "btn btn-sm btn-outline-secondary container" %>
             <%= link_to  "Sign In", new_user_session_path, class: "btn btn-sm btn-outline-success container" %>
      
          </div>
        </div>
      </header>
      

<div class="container">
<br>
      <div class="nav-scroller py-1 mb-2">
      
        <nav class="nav d-flex justify-content-between">
      
          <%= link_to  "Home", root_path, class: "btn btn-outline-info" %>
          <a class="btn btn-outline-info" href="#">India</a>
          <a class="btn btn-outline-info" href="#">Technology</a>
          <a class="btn btn-outline-info" href="#">Design</a>
          <a class="btn btn-outline-info" href="#">Culture</a>
          <a class="btn btn-outline-info" href="#">Programming</a>
          
          <%= link_to  "Ionic Chemistry",  chems_ionics_index_path, class: "btn btn-outline-info" %>
          
          <%= link_to  "Java",  java_index_path, class: "btn btn-outline-info"   %>
          <a class="btn btn-outline-info" href="#">Python</a>
          <a class="btn btn-outline-info" href="#">Health</a>
          <a class="btn btn-outline-info" href="#">Style</a>
          <a class="btn btn-outline-info" href="#">Travel</a>
        </nav>
      </div>
      </div>

      <hr>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
<ul class="nav nav-sidebar">
<li class="sidebar_overview">
hello
</li>
<li class="sidebar_overview">
hello
</li>
<br>
<li class="sidebar_overview">
hello
</li>
<br>

<li class="sidebar_overview">
hello
</li>
<br>

</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    
    <%= stylesheet_link_tag    "application" %>
    
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
<%= render  "layouts/navbar" %>
    <%= yield :sidebar %>

    <%= yield %>
    
    <%= render  "layouts/foot" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>