config/routes.rb
Rails.application.routes.draw do
  
  
  

  devise_for :users
  resources :javaques
  namespace :java do
    resources :jprogresses
  end
  namespace :java do
    get 'article/index'
  end
  namespace :java do
    resources :jps
    
  end
  namespace :chems do
    get 'ionics/index'
  end
  get 'java/progress'
  get 'java/read'
  get 'java/index'
  get 'welcome/home'
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/java.rb
module Java
  def self.table_name_prefix
    'java_'
  end
end

app/models/java/jp.rb
class Java::Jp < ApplicationRecord
  has_one :jprogresss, class_name: "jprogress", foreign_key: "reference_id"
end

app/models/java/jprogress.rb
class Java::Jprogress < ApplicationRecord

 
end

app/controllers/java/article_controller.rb
class Java::ArticleController < ApplicationController
  def index
  end
end

app/controllers/java/jprogresses_controller.rb
class Java::JprogressesController < ApplicationController
  before_action :set_java_jprogress, only: [:show, :edit, :update, :destroy]

  # GET /java/jprogresses
  # GET /java/jprogresses.json
  def index
    @java_jprogresses = Java::Jprogress.all
  end

  # GET /java/jprogresses/1
  # GET /java/jprogresses/1.json
  def show
  end

  # GET /java/jprogresses/new
  def new
    @java_jprogress = Java::Jprogress.new
  end

  # GET /java/jprogresses/1/edit
  def edit
  end

  # POST /java/jprogresses
  # POST /java/jprogresses.json
  def create
    @java_jprogress = Java::Jprogress.new(java_jprogress_params)

    respond_to do |format|
      if @java_jprogress.save
        format.html { redirect_to @java_jprogress, notice: 'Jprogress was successfully created.' }
        format.json { render :show, status: :created, location: @java_jprogress }
      else
        format.html { render :new }
        format.json { render json: @java_jprogress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /java/jprogresses/1
  # PATCH/PUT /java/jprogresses/1.json
  def update
    respond_to do |format|
      if @java_jprogress.update(java_jprogress_params)
        format.html { redirect_to @java_jprogress, notice: 'Jprogress was successfully updated.' }
        format.json { render :show, status: :ok, location: @java_jprogress }
      else
        format.html { render :edit }
        format.json { render json: @java_jprogress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /java/jprogresses/1
  # DELETE /java/jprogresses/1.json
  def destroy
    @java_jprogress.destroy
    respond_to do |format|
      format.html { redirect_to java_jprogresses_url, notice: 'Jprogress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_java_jprogress
      @java_jprogress = Java::Jprogress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def java_jprogress_params
      params.require(:java_jprogress).permit(:heading, :ques, :ans, :point, :input, :output)
    end
end

app/controllers/java/jps_controller.rb
class Java::JpsController < ApplicationController
  before_action :set_java_jp, only: [:show, :edit, :update, :destroy]

  # GET /java/jps
  # GET /java/jps.json
  def index
    @java_jps = Java::Jp.all
  end

  # GET /java/jps/1
  # GET /java/jps/1.json
  def show

  end

  # GET /java/jps/new
  def new
    @java_jp = Java::Jp.new
  end

  # GET /java/jps/1/edit
  def edit

  end

  # POST /java/jps
  # POST /java/jps.json
  def create
    @java_jp = Java::Jp.new(java_jp_params)
    @java_jprogress = Java::Jprogress.new(java_jprogress_params)


    respond_to do |format|
      if @java_jp.save
        #format.html { redirect_to @java_jp, notice: 'Jp was successfully created.' }
        
      else
        format.html { render :new }
        format.json { render json: @java_jp.errors, status: :unprocessable_entity }
      end
    end
      
    end
  

  # PATCH/PUT /java/jps/1
  # PATCH/PUT /java/jps/1.json
  def update   
     @java_jprogress = Java::Jprogress.new(java_jprogress_params)

    respond_to do |format|
      if @java_jp.update(java_jp_params)
        if @java_jprogress.save
          format.html { redirect_to @java_jprogress, notice: 'Jprogress was successfully created.' }
          format.json { render :show, status: :ok, location: @java_jprogress }
        else
          format.json { render json: @java_jprogress.errors, status: :unprocessable_entity }
        end  
        format.html { redirect_to @java_jp, notice: 'Jp was successfully updated.' }
        format.json { render :show, status: :ok, location: @java_jp }
      else
        format.html { render :edit }
        format.json { render json: @java_jp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /java/jps/1
  # DELETE /java/jps/1.json
  def destroy
    @java_jp.destroy
    respond_to do |format|
      format.html { redirect_to java_jps_url, notice: 'Jp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_java_jp
      @java_jp = Java::Jp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def java_jp_params
      params.require(:java_jp).permit(:heading, :ques, :ans, :input, :output, :point, :editor)
    end

    def set_java_jprogress
      @java_jprogress = Java::Jprogress.find(params[:id])
    end

    def java_jprogress_params
      params.require(:java_jprogress).permit(:heading, :ques, :ans, :point, :input, :output)
    end
end

app/controllers/java_controller.rb
class JavaController < ApplicationController
  def read
  end

  def index
  end
 
  def progress
   
  end 
 

 
end

app/helpers/java/article_helper.rb
module Java::ArticleHelper
end

app/helpers/java/jprogresses_helper.rb
module Java::JprogressesHelper
end

app/helpers/java/jps_helper.rb
module Java::JpsHelper
end

app/helpers/java_helper.rb
module JavaHelper
end

app/views/java/index.html.erb
<div class="pos">
<div class="card text-center">
  <div class="card-header bg-dark text-white">
    Prefer Language
  </div>
  <div class="card-body">
    <h1 class="card-title text-danger">Java</h1>
    <h3 class="card-text"></h3>
    <h2><%= link_to  "Continue Reading", java_read_path, class: "btn btn-warning" %></h2>
  </div>
  <div class="card-footer text-muted bg-dark text-primary">
    You visted on 02/07/2018
   </div>
</div>
</div>
      <!-->
      <!-->
      

     <div class="pos2"> 
 <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Article</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto"><br>
        <%= link_to "Article", java_article_index_path,class: "btn btn-warning"%>
            </div>
            <%= image_tag "jpic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>


        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-success">New</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Practice</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 11</div>
              <p class="card-text mb-auto"> <br><br>
       <%= link_to "Practice",  new_javaque_path,class: "btn btn-warning"%>  
          </p>
             
            </div>
           
            <%= image_tag  "ppic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>

      </div>



      
 <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-danger">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Challenge</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto"><br><br>
        <%= link_to "Challenge",  java_jps_path,class: "btn btn-warning"%></p>
            </div>
            
            <%= image_tag "jpic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>


        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-info">Java</strong>
              <h3 class="mb-0">
                <h1 class="text-dark" href="#">Progress</h1>
              </h3>
              <div class="mb-1 text-muted">Nov 11</div>
              <p class="card-text mb-auto"><br><br>
<%= link_to "Progress",   java_jprogresses_path,class: "btn btn-warning"%>
          </p>
             
            </div>
           
            <%= image_tag  "ppic.png", class: "card-img-right flex-auto d-none d-lg-block" %>
          </div>
        </div>
        
      </div>
</div>